swagger: "2.0"
info:
  title: ""
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /modules/meta:
    get:
      tags:
      - modules
      summary: meta modules
      operationId: modules#meta
      responses:
        "200":
          description: OK response.
          schema: {}
      schemes:
      - http
  /projects/{id}/activity:
    get:
      tags:
      - activity
      summary: project activity
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: activity#project
      parameters:
      - name: page
        in: query
        required: false
        type: integer
        format: int64
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ActivityProjectResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/{id}/follow:
    post:
      tags:
      - following
      summary: follow following
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: following#follow
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/FollowingFollowUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/{id}/followers:
    get:
      tags:
      - following
      summary: followers following
      operationId: following#followers
      parameters:
      - name: page
        in: query
        required: false
        type: integer
        format: int64
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/FollowingFollowersResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/FollowingFollowersUnauthorizedResponseBody'
      schemes:
      - http
  /projects/{id}/unfollow:
    post:
      tags:
      - following
      summary: unfollow following
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: following#unfollow
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/FollowingUnfollowUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/{id}/update:
    post:
      tags:
      - project
      summary: update project
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: project#update
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      - name: UpdateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ProjectUpdateRequestBody'
          required:
          - body
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ProjectUpdateUnauthorizedResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ProjectUpdateNotFoundResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/invites/{id}/accept:
    post:
      tags:
      - project
      summary: accept invite project
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: project#accept invite
      parameters:
      - name: token
        in: query
        required: false
        type: string
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ProjectAcceptInviteUnauthorizedResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ProjectAcceptInviteNotFoundResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/invites/{id}/reject:
    post:
      tags:
      - project
      summary: reject invite project
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: project#reject invite
      parameters:
      - name: token
        in: query
        required: false
        type: string
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ProjectRejectInviteUnauthorizedResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ProjectRejectInviteNotFoundResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/invites/{token}:
    get:
      tags:
      - project
      summary: lookup invite project
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: project#lookup invite
      parameters:
      - name: token
        in: path
        required: true
        type: string
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ProjectLookupInviteResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ProjectLookupInviteUnauthorizedResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ProjectLookupInviteNotFoundResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /projects/invites/pending:
    get:
      tags:
      - project
      summary: invites project
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: project#invites
      parameters:
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ProjectInvitesResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/ProjectInvitesUnauthorizedResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ProjectInvitesNotFoundResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /stations/@/{id}/details:
    get:
      tags:
      - station
      summary: station station
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: station#station
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int32
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/StationStationResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/StationStationUnauthorizedResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/StationStationNotFoundResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /stations/{id}/activity:
    get:
      tags:
      - activity
      summary: station activity
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: activity#station
      parameters:
      - name: page
        in: query
        required: false
        type: integer
        format: int64
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: Authorization
        in: header
        description: authentication token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ActivityStationResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /tasks/devices/{deviceId}/refresh:
    post:
      tags:
      - tasks
      summary: refresh device tasks
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: tasks#refresh device
      parameters:
      - name: deviceId
        in: path
        required: true
        type: string
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TasksRefreshDeviceUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /tasks/five:
    get:
      tags:
      - tasks
      summary: five tasks
      operationId: tasks#five
      responses:
        "204":
          description: No Content response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TasksFiveUnauthorizedResponseBody'
      schemes:
      - http
  /test/{id}:
    get:
      tags:
      - test
      summary: get test
      operationId: test#get
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TestGetUnauthorizedResponseBody'
      schemes:
      - http
  /test/email:
    get:
      tags:
      - test
      summary: email test
      description: |2-

        **Required security scopes for jwt**:
          * `api:access`
      operationId: test#email
      parameters:
      - name: address
        in: query
        required: true
        type: string
      - name: Authorization
        in: header
        description: authentication token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TestEmailUnauthorizedResponseBody'
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
  /test/error:
    get:
      tags:
      - test
      summary: error test
      operationId: test#error
      responses:
        "204":
          description: No Content response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/TestErrorUnauthorizedResponseBody'
      schemes:
      - http
definitions:
  ActivityEntryResponseBody:
    title: 'Mediatype identifier: application/vnd.app.activity.entry; view=default'
    type: object
    properties:
      created_at:
        type: integer
        example: 4781490519588557821
        format: int64
      id:
        type: integer
        example: 280926595296192557
        format: int64
      key:
        type: string
        example: Quia velit.
      meta:
        example: Explicabo vel dignissimos sit.
      project:
        $ref: '#/definitions/ProjectSummaryResponseBody'
      station:
        $ref: '#/definitions/StationSummaryResponseBody'
      type:
        type: string
        example: Quisquam qui.
    description: ActivityEntryResponseBody result type (default view)
    example:
      created_at: 1616191176580245674
      id: 4973431729677819677
      key: Voluptas quo sit voluptas deleniti.
      meta: Iure illo odio quod.
      project:
        id: 3935033802229042877
        name: Earum odio.
      station:
        id: 6527264551474073732
        name: Reiciendis voluptatem quisquam.
      type: Modi distinctio ea et.
    required:
    - id
    - key
    - project
    - station
    - created_at
    - type
    - meta
  ActivityEntryResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.app.activity.entry; type=collection;
      view=default'
    type: array
    items:
      $ref: '#/definitions/ActivityEntryResponseBody'
    description: ActivityEntryCollectionResponseBody is the result type for an array
      of ActivityEntryResponseBody (default view)
    example:
    - created_at: 8648786087331153504
      id: 5835085579399476144
      key: Ut et nemo est hic et debitis.
      meta: Aliquam dignissimos quia nobis libero quia.
      project:
        id: 3935033802229042877
        name: Earum odio.
      station:
        id: 6527264551474073732
        name: Reiciendis voluptatem quisquam.
      type: A asperiores consequatur architecto quam fugit dolor.
    - created_at: 8648786087331153504
      id: 5835085579399476144
      key: Ut et nemo est hic et debitis.
      meta: Aliquam dignissimos quia nobis libero quia.
      project:
        id: 3935033802229042877
        name: Earum odio.
      station:
        id: 6527264551474073732
        name: Reiciendis voluptatem quisquam.
      type: A asperiores consequatur architecto quam fugit dolor.
    - created_at: 8648786087331153504
      id: 5835085579399476144
      key: Ut et nemo est hic et debitis.
      meta: Aliquam dignissimos quia nobis libero quia.
      project:
        id: 3935033802229042877
        name: Earum odio.
      station:
        id: 6527264551474073732
        name: Reiciendis voluptatem quisquam.
      type: A asperiores consequatur architecto quam fugit dolor.
  ActivityProjectResponseBody:
    title: 'Mediatype identifier: application/vnd.app.project.activity.page; view=default'
    type: object
    properties:
      activities:
        $ref: '#/definitions/ActivityEntryResponseBodyCollection'
      page:
        type: integer
        example: 1375256375
        format: int32
      total:
        type: integer
        example: 1802595242
        format: int32
    description: ProjectResponseBody result type (default view)
    example:
      activities:
      - created_at: 8648786087331153504
        id: 5835085579399476144
        key: Ut et nemo est hic et debitis.
        meta: Aliquam dignissimos quia nobis libero quia.
        project:
          id: 3935033802229042877
          name: Earum odio.
        station:
          id: 6527264551474073732
          name: Reiciendis voluptatem quisquam.
        type: A asperiores consequatur architecto quam fugit dolor.
      - created_at: 8648786087331153504
        id: 5835085579399476144
        key: Ut et nemo est hic et debitis.
        meta: Aliquam dignissimos quia nobis libero quia.
        project:
          id: 3935033802229042877
          name: Earum odio.
        station:
          id: 6527264551474073732
          name: Reiciendis voluptatem quisquam.
        type: A asperiores consequatur architecto quam fugit dolor.
      - created_at: 8648786087331153504
        id: 5835085579399476144
        key: Ut et nemo est hic et debitis.
        meta: Aliquam dignissimos quia nobis libero quia.
        project:
          id: 3935033802229042877
          name: Earum odio.
        station:
          id: 6527264551474073732
          name: Reiciendis voluptatem quisquam.
        type: A asperiores consequatur architecto quam fugit dolor.
      - created_at: 8648786087331153504
        id: 5835085579399476144
        key: Ut et nemo est hic et debitis.
        meta: Aliquam dignissimos quia nobis libero quia.
        project:
          id: 3935033802229042877
          name: Earum odio.
        station:
          id: 6527264551474073732
          name: Reiciendis voluptatem quisquam.
        type: A asperiores consequatur architecto quam fugit dolor.
      page: 631793275
      total: 655829539
    required:
    - activities
    - total
    - page
  ActivityStationResponseBody:
    title: 'Mediatype identifier: application/vnd.app.station.activity.page; view=default'
    type: object
    properties:
      activities:
        $ref: '#/definitions/ActivityEntryResponseBodyCollection'
      page:
        type: integer
        example: 129914939
        format: int32
      total:
        type: integer
        example: 769677021
        format: int32
    description: StationResponseBody result type (default view)
    example:
      activities:
      - created_at: 8648786087331153504
        id: 5835085579399476144
        key: Ut et nemo est hic et debitis.
        meta: Aliquam dignissimos quia nobis libero quia.
        project:
          id: 3935033802229042877
          name: Earum odio.
        station:
          id: 6527264551474073732
          name: Reiciendis voluptatem quisquam.
        type: A asperiores consequatur architecto quam fugit dolor.
      - created_at: 8648786087331153504
        id: 5835085579399476144
        key: Ut et nemo est hic et debitis.
        meta: Aliquam dignissimos quia nobis libero quia.
        project:
          id: 3935033802229042877
          name: Earum odio.
        station:
          id: 6527264551474073732
          name: Reiciendis voluptatem quisquam.
        type: A asperiores consequatur architecto quam fugit dolor.
      - created_at: 8648786087331153504
        id: 5835085579399476144
        key: Ut et nemo est hic et debitis.
        meta: Aliquam dignissimos quia nobis libero quia.
        project:
          id: 3935033802229042877
          name: Earum odio.
        station:
          id: 6527264551474073732
          name: Reiciendis voluptatem quisquam.
        type: A asperiores consequatur architecto quam fugit dolor.
      - created_at: 8648786087331153504
        id: 5835085579399476144
        key: Ut et nemo est hic et debitis.
        meta: Aliquam dignissimos quia nobis libero quia.
        project:
          id: 3935033802229042877
          name: Earum odio.
        station:
          id: 6527264551474073732
          name: Reiciendis voluptatem quisquam.
        type: A asperiores consequatur architecto quam fugit dolor.
      page: 512389317
      total: 771407072
    required:
    - activities
    - total
    - page
  AvatarResponseBody:
    title: AvatarResponseBody
    type: object
    properties:
      url:
        type: string
        example: Quia voluptas similique aliquam excepturi et nobis.
    example:
      url: Sunt veniam esse et repellendus sit.
    required:
    - url
  FollowerResponseBody:
    title: 'Mediatype identifier: application/vnd.app.follower; view=default'
    type: object
    properties:
      avatar:
        $ref: '#/definitions/AvatarResponseBody'
      id:
        type: integer
        example: 2861495735816618087
        format: int64
      name:
        type: string
        example: Dicta beatae hic eos a provident.
    description: FollowerResponseBody result type (default view)
    example:
      avatar:
        url: Natus eos et occaecati.
      id: 3894107913239411830
      name: Sit iste voluptas ut.
    required:
    - id
    - name
  FollowerResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.app.follower; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/FollowerResponseBody'
    description: FollowerCollectionResponseBody is the result type for an array of
      FollowerResponseBody (default view)
    example:
    - avatar:
        url: Natus eos et occaecati.
      id: 5383157966376952469
      name: Facilis numquam commodi ut.
    - avatar:
        url: Natus eos et occaecati.
      id: 5383157966376952469
      name: Facilis numquam commodi ut.
  FollowingFollowUnauthorizedResponseBody:
    title: FollowingFollowUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Odio maxime.
  FollowingFollowersResponseBody:
    title: 'Mediatype identifier: application/vnd.app.followers; view=default'
    type: object
    properties:
      followers:
        $ref: '#/definitions/FollowerResponseBodyCollection'
      page:
        type: integer
        example: 1752246910
        format: int32
      total:
        type: integer
        example: 180067423
        format: int32
    description: FollowersResponseBody result type (default view)
    example:
      followers:
      - avatar:
          url: Natus eos et occaecati.
        id: 5383157966376952469
        name: Facilis numquam commodi ut.
      - avatar:
          url: Natus eos et occaecati.
        id: 5383157966376952469
        name: Facilis numquam commodi ut.
      - avatar:
          url: Natus eos et occaecati.
        id: 5383157966376952469
        name: Facilis numquam commodi ut.
      page: 1060617020
      total: 1725135840
    required:
    - followers
    - total
    - page
  FollowingFollowersUnauthorizedResponseBody:
    title: FollowingFollowersUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Fugiat omnis sed vel.
  FollowingUnfollowUnauthorizedResponseBody:
    title: FollowingUnfollowUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Quo et eum ut reprehenderit libero.
  ImageRefResponseBody:
    title: ImageRefResponseBody
    type: object
    properties:
      url:
        type: string
        example: Consequatur omnis molestiae aut.
    example:
      url: Aperiam voluptatem perspiciatis libero minus et nesciunt.
    required:
    - url
  PendingInviteResponseBody:
    title: PendingInviteResponseBody
    type: object
    properties:
      id:
        type: integer
        example: 2587552997851748059
        format: int64
      project:
        $ref: '#/definitions/ProjectSummaryResponseBody'
      time:
        type: integer
        example: 4134045918724087180
        format: int64
    example:
      id: 1245164885861824327
      project:
        id: 3935033802229042877
        name: Earum odio.
      time: 795987181610422048
    required:
    - id
    - project
    - time
  ProjectAcceptInviteNotFoundResponseBody:
    title: ProjectAcceptInviteNotFoundResponseBody
    type: string
    description: not found
    example: Est omnis.
  ProjectAcceptInviteUnauthorizedResponseBody:
    title: ProjectAcceptInviteUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Excepturi est veritatis ratione doloremque quia.
  ProjectInvitesNotFoundResponseBody:
    title: ProjectInvitesNotFoundResponseBody
    type: string
    description: not found
    example: Velit non saepe quos aliquid totam.
  ProjectInvitesResponseBody:
    title: 'Mediatype identifier: application/vnd.app.invites.pending; view=default'
    type: object
    properties:
      pending:
        type: array
        items:
          $ref: '#/definitions/PendingInviteResponseBody'
        example:
        - id: 7134691977437916367
          project:
            id: 3935033802229042877
            name: Earum odio.
          time: 1061947067536649931
        - id: 7134691977437916367
          project:
            id: 3935033802229042877
            name: Earum odio.
          time: 1061947067536649931
        - id: 7134691977437916367
          project:
            id: 3935033802229042877
            name: Earum odio.
          time: 1061947067536649931
        - id: 7134691977437916367
          project:
            id: 3935033802229042877
            name: Earum odio.
          time: 1061947067536649931
    description: InvitesResponseBody result type (default view)
    example:
      pending:
      - id: 7134691977437916367
        project:
          id: 3935033802229042877
          name: Earum odio.
        time: 1061947067536649931
      - id: 7134691977437916367
        project:
          id: 3935033802229042877
          name: Earum odio.
        time: 1061947067536649931
      - id: 7134691977437916367
        project:
          id: 3935033802229042877
          name: Earum odio.
        time: 1061947067536649931
    required:
    - pending
  ProjectInvitesUnauthorizedResponseBody:
    title: ProjectInvitesUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Voluptas esse occaecati voluptates.
  ProjectLookupInviteNotFoundResponseBody:
    title: ProjectLookupInviteNotFoundResponseBody
    type: string
    description: not found
    example: Sequi aliquam velit eveniet.
  ProjectLookupInviteResponseBody:
    title: 'Mediatype identifier: application/vnd.app.invites.pending; view=default'
    type: object
    properties:
      pending:
        type: array
        items:
          $ref: '#/definitions/PendingInviteResponseBody'
        example:
        - id: 7134691977437916367
          project:
            id: 3935033802229042877
            name: Earum odio.
          time: 1061947067536649931
        - id: 7134691977437916367
          project:
            id: 3935033802229042877
            name: Earum odio.
          time: 1061947067536649931
    description: Lookup InviteResponseBody result type (default view)
    example:
      pending:
      - id: 7134691977437916367
        project:
          id: 3935033802229042877
          name: Earum odio.
        time: 1061947067536649931
      - id: 7134691977437916367
        project:
          id: 3935033802229042877
          name: Earum odio.
        time: 1061947067536649931
      - id: 7134691977437916367
        project:
          id: 3935033802229042877
          name: Earum odio.
        time: 1061947067536649931
      - id: 7134691977437916367
        project:
          id: 3935033802229042877
          name: Earum odio.
        time: 1061947067536649931
    required:
    - pending
  ProjectLookupInviteUnauthorizedResponseBody:
    title: ProjectLookupInviteUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Labore doloribus voluptas consequuntur illum dolores quo.
  ProjectRejectInviteNotFoundResponseBody:
    title: ProjectRejectInviteNotFoundResponseBody
    type: string
    description: not found
    example: Fugit impedit quidem labore autem.
  ProjectRejectInviteUnauthorizedResponseBody:
    title: ProjectRejectInviteUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Et quis optio voluptatibus quas dolor.
  ProjectSummaryResponseBody:
    title: ProjectSummaryResponseBody
    type: object
    properties:
      id:
        type: integer
        example: 4341575906931714311
        format: int64
      name:
        type: string
        example: Fugiat quas ex natus.
    example:
      id: 5613084908585335094
      name: Est quidem deleniti necessitatibus fugiat velit sed.
    required:
    - id
    - name
  ProjectUpdateNotFoundResponseBody:
    title: ProjectUpdateNotFoundResponseBody
    type: string
    description: not found
    example: Neque harum.
  ProjectUpdateRequestBody:
    title: ProjectUpdateRequestBody
    type: object
    properties:
      body:
        type: string
        example: Aut dolor est sequi vel velit eos.
    example:
      body: Est aut iste earum qui.
    required:
    - body
  ProjectUpdateUnauthorizedResponseBody:
    title: ProjectUpdateUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Quibusdam aliquid.
  StationOwnerResponseBody:
    title: StationOwnerResponseBody
    type: object
    properties:
      id:
        type: integer
        example: 1982095326
        format: int32
      name:
        type: string
        example: Consequatur omnis rerum et pariatur.
    example:
      id: 1546546432
      name: Dignissimos illum ab adipisci consequatur et facilis.
    required:
    - id
    - name
  StationPhotosResponseBody:
    title: StationPhotosResponseBody
    type: object
    properties:
      small:
        type: string
        example: Perspiciatis magnam fugiat repellendus.
    example:
      small: Aut eos tenetur.
    required:
    - small
  StationStationNotFoundResponseBody:
    title: StationStationNotFoundResponseBody
    type: string
    description: not found
    example: Quasi dolorem placeat a.
  StationStationResponseBody:
    title: 'Mediatype identifier: application/vnd.app.station.full; view=default'
    type: object
    properties:
      device_id:
        type: string
        example: Corporis quam rerum omnis.
      id:
        type: integer
        example: 1742609606
        format: int32
      images:
        type: array
        items:
          $ref: '#/definitions/ImageRefResponseBody'
        example:
        - url: Hic aut nam et similique qui.
        - url: Hic aut nam et similique qui.
      name:
        type: string
        example: Aliquam aut est.
      owner:
        $ref: '#/definitions/StationOwnerResponseBody'
      photos:
        $ref: '#/definitions/StationPhotosResponseBody'
      read_only:
        type: boolean
        example: false
      uploads:
        type: array
        items:
          $ref: '#/definitions/StationUploadResponseBody'
        example:
        - blocks:
          - 190588057897244188
          - 5154687276973302881
          - 2546252234366462519
          id: 2920417339524806997
          size: 5430013960920797921
          time: 8354332868448807316
          type: Enim ipsum molestias.
          upload_id: Optio voluptatibus quis exercitationem autem cumque.
          url: Odio voluptatem dolorem.
        - blocks:
          - 190588057897244188
          - 5154687276973302881
          - 2546252234366462519
          id: 2920417339524806997
          size: 5430013960920797921
          time: 8354332868448807316
          type: Enim ipsum molestias.
          upload_id: Optio voluptatibus quis exercitationem autem cumque.
          url: Odio voluptatem dolorem.
    description: StationResponseBody result type (default view)
    example:
      device_id: Et omnis consectetur assumenda.
      id: 834376722
      images:
      - url: Hic aut nam et similique qui.
      - url: Hic aut nam et similique qui.
      - url: Hic aut nam et similique qui.
      - url: Hic aut nam et similique qui.
      name: Sit ipsam consequatur impedit voluptatem facere corporis.
      owner:
        id: 1158021204
        name: Corrupti voluptas neque.
      photos:
        small: Atque ut ab aliquam in assumenda magni.
      read_only: false
      uploads:
      - blocks:
        - 190588057897244188
        - 5154687276973302881
        - 2546252234366462519
        id: 2920417339524806997
        size: 5430013960920797921
        time: 8354332868448807316
        type: Enim ipsum molestias.
        upload_id: Optio voluptatibus quis exercitationem autem cumque.
        url: Odio voluptatem dolorem.
      - blocks:
        - 190588057897244188
        - 5154687276973302881
        - 2546252234366462519
        id: 2920417339524806997
        size: 5430013960920797921
        time: 8354332868448807316
        type: Enim ipsum molestias.
        upload_id: Optio voluptatibus quis exercitationem autem cumque.
        url: Odio voluptatem dolorem.
      - blocks:
        - 190588057897244188
        - 5154687276973302881
        - 2546252234366462519
        id: 2920417339524806997
        size: 5430013960920797921
        time: 8354332868448807316
        type: Enim ipsum molestias.
        upload_id: Optio voluptatibus quis exercitationem autem cumque.
        url: Odio voluptatem dolorem.
    required:
    - id
    - name
    - owner
    - device_id
    - uploads
    - images
    - photos
    - read_only
  StationStationUnauthorizedResponseBody:
    title: StationStationUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Quia natus.
  StationSummaryResponseBody:
    title: StationSummaryResponseBody
    type: object
    properties:
      id:
        type: integer
        example: 71959842371533053
        format: int64
      name:
        type: string
        example: Repellendus atque perspiciatis quo beatae magnam et.
    example:
      id: 3378666266697758838
      name: Est voluptatem possimus sint sint aut.
    required:
    - id
    - name
  StationUploadResponseBody:
    title: StationUploadResponseBody
    type: object
    properties:
      blocks:
        type: array
        items:
          type: integer
          example: 5675808951244207212
          format: int64
        example:
        - 8077413289712931019
        - 4709161023334643932
        - 7305042128034328460
      id:
        type: integer
        example: 6546237315506585011
        format: int64
      size:
        type: integer
        example: 5890121434226169022
        format: int64
      time:
        type: integer
        example: 3298028782423943191
        format: int64
      type:
        type: string
        example: Et id fuga ad aut consequuntur et.
      upload_id:
        type: string
        example: Sequi qui.
      url:
        type: string
        example: Minima dignissimos.
    example:
      blocks:
      - 343192541494198032
      - 6939903678658135773
      - 9220583740525450439
      id: 3533639455505033779
      size: 8318051413112630202
      time: 4012211043050441801
      type: Voluptatem dolorum ut libero ducimus vitae.
      upload_id: Dolor omnis.
      url: Voluptate est.
    required:
    - id
    - time
    - upload_id
    - size
    - url
    - type
    - blocks
  TasksFiveUnauthorizedResponseBody:
    title: TasksFiveUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Aut qui ea fuga.
  TasksRefreshDeviceUnauthorizedResponseBody:
    title: TasksRefreshDeviceUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Adipisci debitis eaque esse cupiditate ducimus.
  TestEmailUnauthorizedResponseBody:
    title: TestEmailUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Cupiditate et.
  TestErrorUnauthorizedResponseBody:
    title: TestErrorUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Exercitationem delectus totam eaque exercitationem illo dicta.
  TestGetUnauthorizedResponseBody:
    title: TestGetUnauthorizedResponseBody
    type: string
    description: credentials are invalid
    example: Ut quam aliquid quo voluptate atque qui.
securityDefinitions:
  jwt_header_Authorization:
    type: apiKey
    description: |2-

      **Security Scopes**:
        * `api:access`: API access
        * `api:admin`: API admin access
        * `api:ingestion`: Ingestion access
    name: Authorization
    in: header
